export const meta = {
  date: "Wednesday 18 March 2026",
  meetTime: "12:45pm",
  meetPlace: "Cardiff Central Station",
  sunrise: "6:24am",
  sunset: "6:21pm",
  daylight: "11hrs 56mins",
  weather: "Morning showers clearing, cloud & sun in the afternoon",
  temp: "~15°C",
  tideLow: "1:17pm (0.7m)",
  tideHigh: "7:00pm (11.6m)",
  tideWarning: "Bristol Channel has one of the highest tidal ranges in the world — rises very fast after 2pm",
};

export const stops = [
  {
    time: "12:45pm",
    endTime: "~1:15pm",
    title: "Cardiff Central → Barry Island",
    icon: "🚉",
    duration: "30 min train",
    accent: "#A8D8B9",
    description: "Direct train, no changes. 29–34 mins, every ~30 mins on Transport for Wales. ~£5 return per person.",
    tips: [
      "Grab snacks/drinks at the station before boarding — nothing good on this train",
      "Sit on the right side for sea glimpses as you approach Barry Island",
    ],
    quote: null,
  },
  {
    time: "~1:15pm",
    endTime: "~2:00pm",
    title: "Barry Island",
    icon: "🎡",
    duration: "~45 mins",
    accent: "#F4A261",
    description: "Classic British seaside. Off-season in March it has an eerie, half-empty charm — arcades not fully open, sea wind, everything smelling faintly of vinegar. Made famous by Gavin & Stacey.",
    tips: [
      "Boofy's or O'Shea's for chips — these are the local picks",
      "Avoid Marco's (the tourist trap — overpriced, always in guides)",
      "Eat chips on the sea wall, not inside",
      "Arcades are half the fun off-season — mostly empty, slightly melancholy, very British",
    ],
    quote: "The chaos. Chips in the wind. British seaside at its most gloriously unpolished. Better in March when the crowds are gone.",
  },
  {
    time: "~2:15pm",
    endTime: "~3:00pm",
    title: "Cold Knap Beach",
    icon: "🪨",
    duration: "~45 mins",
    accent: "#E8C890",
    description: "A quieter pebble beach 1 mile west along the coast path. Rock pools exposed at low tide, dramatic geology in the cliffs. Almost no tourists — the crowd drops off completely.",
    tips: [
      "20 min flat walk from Barry Island along the coast path",
      "Bring something to skim on the pebbles",
      "Good footwear essential — pebbles are uneven",
      "Mission: find the Roman ruins (2nd century bathhouse) on the headland — free, no signage, no gift shop",
    ],
    quote: "The secret. Roman ruins with no ticket booth. Rock pools at low tide. The bit people don't expect.",
  },
  {
    time: "~3:00pm",
    endTime: "~4:15pm",
    title: "The Goodsheds, Barry",
    icon: "🍺",
    duration: "~1 hr 15 mins",
    accent: "#C9B8E8",
    description: "Converted shipping container street food market and bar. Multiple independent food traders, craft beer, rooftop terrace. One of the best food/drink spots in the Vale of Glamorgan.",
    tips: [
      "Wednesday afternoon — should be quiet, no queues",
      "Rooftop is worth it even if cold — bring a layer",
      "Budget ~£10–15 for food, ~£5–8 for drinks",
    ],
    quote: "The warmth. Where you sit down, eat properly, and realise you've had a good day. Craft beer, rooftop, no pretension.",
  },
  {
    time: "~4:15pm",
    endTime: "~4:55pm",
    title: "Train to Penarth",
    icon: "🚆",
    duration: "~40 mins",
    accent: "#7EC8E3",
    description: "Barry Island → Cardiff Central (change) → Penarth. Simple change, same operator, platform usually nearby. ~£4 return per person.",
    tips: [
      "Check tfw.wales for exact departure times on the day",
      "The Cardiff Central change is simple — same operator",
      "Penarth station is a short flat walk from the cliff gardens",
    ],
    quote: null,
  },
  {
    time: "~5:00pm",
    endTime: "6:21pm",
    title: "Penarth Cliff Gardens",
    icon: "🌅",
    duration: "~1 hr 25 mins",
    accent: "#FDE68A",
    description: "Victorian seaside town on a headland facing due west over the Bristol Channel. The cliff gardens sit above the famous pier and look directly into the sunset. Best accessible sunset viewpoint near Cardiff.",
    tips: [
      "Bring a layer — cliff headlands catch the wind",
      "Walk the pier end for the best unobstructed western view",
      "Golden hour starts ~5:35pm — be on the headland by 6:00pm latest",
      "This is the payoff for the whole day — don't rush off early",
    ],
    quote: "The payoff. Due west over open water. Victorian pier below. Golden hour over the Bristol Channel. The reason you didn't just go home after lunch.",
    highlight: true,
  },
  {
    time: "7:00pm",
    endTime: "7:11pm",
    title: "Train Home",
    icon: "🏠",
    duration: "11 mins",
    accent: "#A8D8B9",
    description: "First train after sunset. 11 minutes direct to Cardiff Central. Evening free!",
    tips: [],
    quote: null,
  },
];

export const costs = [
  { item: "Train: Cardiff → Barry return", amount: "~£5" },
  { item: "Train: Cardiff → Penarth return", amount: "~£4" },
  { item: "Chips at Barry Island", amount: "~£5" },
  { item: "Lunch at Goodsheds", amount: "~£12" },
  { item: "Drinks at Goodsheds", amount: "~£7" },
  { item: "Cold Knap taxi (optional, split)", amount: "~£2" },
];

export const totalCost = "~£29–35";
