export const meta = {
  date: "Wednesday 18 March 2026",
  meetTime: "12:45pm",
  meetPlace: "Cardiff Central Station",
  subtitle: "Cardiff Central · Barry Island · Cold Knap · Goodsheds · Penarth",
  sunrise: "6:24am",
  sunset: "6:21pm",
  daylight: "11hrs 56mins",
  weather: "Morning showers clearing, cloud & sun in the afternoon",
  temp: "~15°C",
  tideLow: "1:17pm (0.7m)",
  tideHigh: "7:00pm (11.6m)",
  tideWarning: "Low tide is 1:17pm. Take the Uber from Barry Island — the walk takes 28 mins and the Bristol Channel won't wait. Arriving at Cold Knap by 1:40pm gives you the rock pools and beach at their best.",
};

export const stops = [
  {
    time: "12:45pm",
    title: "Meet at Cardiff Central",
    icon: "🚉",
    duration: "30 min train",
    accent: "#A8D8B9",
    description: "Meet at the main departures board. Train leaves at 12:59pm — be on the platform by 12:50pm. Direct train to Barry Island, ~30 mins, Transport for Wales. Runs every 30 mins. ~£5 return per person.",
    tips: [
      "Grab snacks/drinks at the station before boarding — nothing good on this train",
      "Sit on the right side for sea glimpses as you approach Barry Island",
    ],
    quote: null,
  },
  {
    time: "1:30pm",
    title: "Barry Island — O'Shea's Chips",
    icon: "🍟",
    duration: "~5 mins",
    accent: "#F4A261",
    description: "Arrive Barry Island. Go straight to O'Shea's for chips and head immediately to the Uber pickup. Barry Island is the chip stop only on the way in — the tide won't wait.",
    tips: [
      "O'Shea's — the local pick for chips",
      "Grab and go. Head straight to the Uber.",
    ],
    quote: null,
  },
  {
    time: "1:30–1:40pm",
    title: "Uber to Cold Knap",
    icon: "🚗",
    duration: "6 min ride",
    accent: "#F4A261",
    highlight: true,
    description: "6 min Uber, ~£5–6 split between the group. This is not optional.",
    whyUber: true,
    tips: [],
    quote: null,
  },
  {
    time: "1:40pm",
    title: "Cold Knap Beach",
    icon: "🪨",
    duration: "~45 mins",
    accent: "#7EC8E3",
    description: "Arrive 23 minutes after low tide — rock pools and beach still well exposed. Pebble beach with sand at low tide, rock pools, sedimentary cliff strata at the western end. The Roman ruins here are a 3rd-century mansio — an official Roman guest house for visitors arriving at the old harbour. A scheduled ancient monument with no entry fee and no gift shop, just sitting on the headland. Harp-shaped lake behind the beach. Leave by 2:25pm.",
    tips: [
      "Rock pools at their best right now — only 23 mins after low tide",
      "Good footwear essential — pebbles are uneven",
      "Mission: find the Roman ruins on the headland",
    ],
    quote: "The secret. Roman ruins with no ticket booth. Rock pools at low tide. The bit people don't expect.",
  },
  {
    time: "2:25pm",
    title: "Walk to Goodsheds",
    icon: "🚶",
    duration: "~30 min walk",
    accent: "#E8C890",
    description: "Walk east along the flat seafront promenade back toward Barry. 30 min walk, coast the whole way. This is the wind-down from Cold Knap — sea air, flat path, easy going.",
    tips: [
      "Flat, easy promenade — no hills, no navigation",
      "Sea views the whole way",
    ],
    quote: null,
  },
  {
    time: "2:55pm",
    title: "The Goodsheds, Barry",
    icon: "🍺",
    duration: "~1 hr",
    accent: "#C9B8E8",
    description: "Converted shipping container street food market and bar at Barry Waterfront. Independent food vendors, craft beer at Craft Republic next door, rooftop bar. No booking needed for lunch — grab a free table.",
    address: "Hood Road, Barry, CF62 5QU",
    openNote: "Open Wed–Sun only",
    tips: [
      "Wednesday afternoon — should be quiet, no queues",
      "Rooftop bar is worth it even if cold — bring a layer",
      "Budget ~£12–15 for food, ~£5–8 for drinks",
    ],
    quote: "The warmth. Where you sit down, eat properly, and realise you've had a good day. Craft beer, rooftop, no pretension.",
  },
  {
    time: "4:00pm",
    title: "Barry Island (proper visit)",
    icon: "🎡",
    duration: "~45 mins",
    accent: "#F4A261",
    description: "Just a 5–10 min walk from Goodsheds. Now you can actually enjoy it — full, warm, no tide pressure. Walk Whitmore Bay, hit the arcades, walk the sea wall. The classic British seaside in full effect.",
    tips: [
      "Arcades are half the fun off-season — mostly empty, slightly melancholy, very British",
      "Walk the full length of Whitmore Bay",
    ],
    quote: null,
  },
  {
    time: "4:45pm",
    title: "Train to Penarth",
    icon: "🚆",
    duration: "~40 mins",
    accent: "#A8D8B9",
    description: "Barry Island → Cardiff Central (~30 mins), change platforms, Cardiff Central → Penarth (~11 mins). Total ~40 mins. Arrive Penarth ~5:15pm. Check tfw.wales for exact times on the day.",
    tips: [
      "The Cardiff Central change is simple — same operator, platform usually nearby",
      "Penarth station is a short flat walk from the cliff gardens",
    ],
    quote: null,
  },
  {
    time: "5:15pm",
    title: "Penarth Cliff Gardens",
    icon: "🌿",
    duration: "~1 hr",
    accent: "#FDE68A",
    description: "Headland faces due west over the Bristol Channel — best accessible sunset viewpoint near Cardiff. Walk the cliff path, Victorian pier below is free to walk. Find a spot on the headland. Golden hour begins around 5:35pm. Be at the cliff edge by 6:00pm at the latest.",
    tips: [
      "Bring a layer — cliff headlands catch the wind",
      "Walk the pier end for the best unobstructed western view",
      "Golden hour starts ~5:35pm — be on the headland by 6:00pm latest",
      "This is the payoff for the whole day — don't rush off early",
    ],
    quote: "The payoff. Due west over open water. Victorian pier below. Golden hour over the Bristol Channel. The reason you didn't just go home after lunch.",
  },
  {
    time: "6:21pm",
    title: "Sunset",
    icon: "☀️",
    duration: null,
    accent: "#F4A261",
    description: "Sun sets over the Bristol Channel. 11 hours 56 minutes of daylight ends here. The whole day was building to this.",
    tips: [],
    quote: null,
    highlight: true,
  },
  {
    time: "7:00pm",
    title: "Train Home",
    icon: "🏠",
    duration: "11 mins",
    accent: "#A8D8B9",
    description: "Penarth → Cardiff Central, 11 minutes. Back by 7:11pm. Evening free.",
    tips: [],
    quote: null,
  },
];

export const costs = [
  { item: "Trains (all legs)", amount: "~£9" },
  { item: "Uber to Cold Knap (split)", amount: "~£2pp" },
  { item: "Chips at O'Shea's", amount: "~£5" },
  { item: "Food + drinks at Goodsheds", amount: "~£18" },
];

export const totalCost = "~£34";

export const rules = [
  "Uber from Barry Island. Do not walk — the tide won't wait.",
  "Chips from O'Shea's. Eat them in the Uber.",
  "Someone MUST find the Roman ruins at Cold Knap.",
  "Stay for the full sunset — it sets at exactly 6:21pm.",
  "Shoes you don't mind getting wet.",
];
