export const meta = {
  date: "Wednesday 18 March 2026",
  meetTime: "12:45pm",
  meetPlace: "Cardiff Central Station",
  sunrise: "6:24am",
  sunset: "6:21pm",
  daylight: "11hrs 56mins",
  weather: "Morning showers clearing, cloud & sun in the afternoon",
  temp: "~15°C",
  tideLow: "1:17pm (0.7m)",
  tideHigh: "7:00pm (11.6m)",
  tideWarning: "Low tide is 1:17pm — arriving at Cold Knap at 1:35pm means the beach and rock pools are at their best. The Bristol Channel has one of the highest tidal ranges in the world — don't hang around past 3pm.",
};

export const stops = [
  {
    time: "12:45pm",
    endTime: "~1:15pm",
    title: "Meet at Cardiff Central",
    icon: "🚉",
    duration: "30 min train",
    accent: "#A8D8B9",
    description: "Direct train to Barry Island. 30 mins, Transport for Wales, runs every 30 mins. ~£5 return per person.",
    tips: [
      "Grab snacks/drinks at the station before boarding — nothing good on this train",
      "Sit on the right side for sea glimpses as you approach Barry Island",
    ],
    quote: null,
  },
  {
    time: "1:15pm",
    endTime: "1:20pm",
    title: "Barry Island — Chips Stop",
    icon: "🍟",
    duration: "~5 mins",
    accent: "#F4A261",
    description: "Arrive, grab chips from Boofy's or O'Shea's (not Marco's — tourist trap), and immediately start walking west. Barry Island is the chip stop, not a destination today.",
    tips: [
      "Boofy's or O'Shea's — these are the local picks",
      "Do NOT sit down. Grab and go.",
      "Skip Marco's — overpriced, always in guides, never worth it",
    ],
    quote: "Chips in the wind. British seaside at its most gloriously unpolished.",
  },
  {
    time: "1:15–1:35pm",
    endTime: "1:35pm",
    title: "Walk to Cold Knap Eating Chips",
    icon: "🚶",
    duration: "20 min walk",
    accent: "#E8C890",
    description: "20 min walk west along the flat seafront promenade. Eating chips while walking. This is the journey, not dead time — sea views the whole way.",
    tips: [
      "Flat, easy promenade walk — no hills, no navigation",
      "Sea on your left the whole way",
    ],
    quote: null,
  },
  {
    time: "1:35pm",
    endTime: "~3:00pm",
    title: "Cold Knap Beach",
    icon: "🪨",
    duration: "~1 hr 15 mins",
    accent: "#7EC8E3",
    description: "Arriving at almost exactly low tide (1:17pm) — best possible window for exposed rock pools, full beach, and cliff strata. Pebble beach, sedimentary cliff geology, harp-shaped Knap Lake behind.",
    tips: [
      "Rock pools at their absolute best right now — low tide was 18 mins ago",
      "Good footwear essential — pebbles are uneven",
      "Bring something to skim on the pebbles",
      "Mission: find the Roman ruins — a 3rd-century mansio (official guest lodging for harbour visitors). Scheduled ancient monument, no entry fee, no gift shop, just sitting on the headland",
    ],
    quote: "The secret. Roman ruins with no ticket booth. Rock pools at low tide. The bit people don't expect.",
  },
  {
    time: "3:00pm",
    endTime: "~4:15pm",
    title: "The Goodsheds, Barry Town",
    icon: "🍺",
    duration: "~1 hr 15 mins",
    accent: "#C9B8E8",
    description: "Short walk or ~£5 taxi from Cold Knap (~10 mins). Converted shipping container street food market. Craft beer, rooftop terrace. The place to sit down, warm up, and eat properly.",
    tips: [
      "Wednesday afternoon — should be quiet, no queues",
      "Rooftop is worth it even if cold — bring a layer",
      "Budget ~£10–15 for food, ~£5–8 for drinks",
    ],
    quote: "The warmth. Where you sit down, eat properly, and realise you've had a good day. Craft beer, rooftop, no pretension.",
  },
  {
    time: "4:15pm",
    endTime: "~4:55pm",
    title: "Train to Penarth",
    icon: "🚆",
    duration: "~40 mins",
    accent: "#A8D8B9",
    description: "Barry Island → Cardiff Central (~30 mins), change, Cardiff Central → Penarth (~11 mins). Simple change, same operator. Arrive Penarth ~4:55pm.",
    tips: [
      "Check tfw.wales for exact departure times on the day",
      "The Cardiff Central change is simple — same operator, platform usually nearby",
      "Penarth station is a short flat walk from the cliff gardens",
    ],
    quote: null,
  },
  {
    time: "5:00pm",
    endTime: "6:21pm",
    title: "Penarth Cliff Gardens",
    icon: "🌅",
    duration: "~1 hr 25 mins",
    accent: "#FDE68A",
    description: "Headland faces due west over the Bristol Channel. Best accessible sunset spot near Cardiff. Walk the cliff path, optional pier walk below. Golden hour starts ~5:35pm.",
    tips: [
      "Bring a layer — cliff headlands catch the wind",
      "Walk the pier end for the best unobstructed western view",
      "Golden hour starts ~5:35pm — be on the headland by 6:00pm latest",
      "This is the payoff for the whole day — don't rush off early",
    ],
    quote: "The payoff. Due west over open water. Victorian pier below. Golden hour over the Bristol Channel. The reason you didn't just go home after lunch.",
    highlight: true,
  },
  {
    time: "6:21pm",
    endTime: null,
    title: "Sunset",
    icon: "☀️",
    duration: null,
    accent: "#F4A261",
    description: "Sun sets over the Bristol Channel. 11 hrs 56 mins of daylight ends here.",
    tips: [],
    quote: null,
    highlight: true,
  },
  {
    time: "7:00pm",
    endTime: "7:11pm",
    title: "Train Home",
    icon: "🏠",
    duration: "11 mins",
    accent: "#A8D8B9",
    description: "Penarth → Cardiff Central, 11 mins direct. Back by 7:11pm. Evening free!",
    tips: [],
    quote: null,
  },
];

export const costs = [
  { item: "Train: Cardiff → Barry return", amount: "~£5" },
  { item: "Train: Cardiff → Penarth return", amount: "~£4" },
  { item: "Chips at Barry Island", amount: "~£5" },
  { item: "Lunch at Goodsheds", amount: "~£12" },
  { item: "Drinks at Goodsheds", amount: "~£7" },
];

export const totalCost = "~£30–35";

export const rules = [
  "Get chips at Barry and walk immediately. No lingering.",
  "Someone MUST find the Roman ruins at Cold Knap.",
  "Stay for the full sunset — it sets at exactly 6:21pm.",
  "Shoes you don't mind getting wet.",
];
